// This file is auto-generated by scripts/generate-turn-env.js
// Do not edit this file manually.

// IMPORTANT: Replace 'yourdomain.com' with the actual public IP address or domain
// of the machine running the Docker container. For local testing, 'localhost'
// might work if the browser and server are on the same machine.
export const turnServerConfig = {
    urls: 'turn:yourdomain.com:3478',
};
