/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120454-g16d663d371-20250803"
#endif /* AVUTIL_FFVERSION_H */
