// This file is a placeholder and will be auto-generated by scripts/generate-turn-env.js
// Run `npm run setup` to generate the correct configuration.
// Do not edit this file manually.

export const TURN_SECRET = "placeholder-secret-run-setup-script";
